### ISSUE TITLE
使用 docker 搭建 cifs 服务共享配置文件夹

### ISSUE THREAD

**Issue by shynome** [shynome/shynome.github.io#18]
使用下面这个仓库: https://github.com/dperson/samba

运行命令(使用时把备注去掉):
```sh
docker run -d --name samba \
  -p 139:139 -p 445:445 \
  # 挂载要共享的文件夹
  -v /tmp/test:/test \
  dperson/samba \
  # 创建用户并设置密码
  -u 'test;test' \
  # 设置要共享的文件夹
  -s 'test;/test;no;no;no;test' \
  # 修复文件夹权限不对导致无法上传的问题
  -p
```

**Comment by shynome** [comment]
docker 使用 windows 共享文件夹
```yml
volumes: 
  data_www:
    driver_opts: 
      type: 'cifs'
      device: '//server/path/to/share'
      o: 'username=myuser,password=mypw,file_mode=0777,dir_mode=0777'
```
