### ISSUE TITLE
vscode remote container 使用小记

### ISSUE THREAD

**Issue by shynome** [shynome/shynome.github.io#24]
vscode 远程开发的三个插件现在可以在 vscode1.35 正式版上运行了，分别是
基于 `ssh`, `docker` 和 `wsl` 的，`ssh` 的我已经用了一会了, 感觉很好用, 
但还是有个缺点就是多个开发环境的话还是会互相污染, 所以这次来试下基于 docker 容器的远程开发
**注:** 远程开发的插件并不适用于客户端开发. <del>目前想找个方案在里面开发 flutter 想不到可用的方案</del>

先来介绍下我的工作环境是 windows, docker 是直接跑在虚拟机里面, 
因此 docker 的单个 Dockerfile 的模式是行不通的了, 只能使用 docker-compose 模式, 
然后继续介绍工作环境, windows 上只有 docker docker-compose 的命令, 没有跑 docker for windwos 客户端, 
而是设置 DOCKER_HOST='tcp://vm-01:2375' 环境变量来连接 docker 服务器

文件目录结构
```yml
.devcontainer
  # 定义要使用的共享卷并挂载
  - docker-compose.yml
  # 关于这个文件请参考 https://aka.ms/vscode-remote/devcontainer.json
  - devcontainer.json
docker-compose.yml
```

根目录 和 `.devcontainer` 各有一个 `docker-compose.yml`, 后面的 `docker-compose.yml` 会合并前面的, 
`.devcontainer` 下的不要提交因为我们要在这个文件里写 `windows` 共享卷挂和端口映射, 这次以 `php` 的
开发环境来做示例

```yml
# .devcontainer/docker-compose.yml
version: "3.6"

services: 
  php:
    # 感觉比较好的镜像
    image: devilbox/php-fpm:7.2-work
    # 开发模式下没必要启动 php-fpm
    entrypoint: php
    command: [ "-S","0.0.0.0:80", "-t", "/www" ]
    ports: 
    - 80:80
    volumes: 
    - work_v1:/www

volumes: 
  # 建议加个版本号
  work_v1:
    driver_opts: 
      # windows 的共享文件夹的挂载类型
      type: cifs
      # 用的 oracle virtualbox vm , 默认的宿主机就是 192.168.56.1
      device: //192.168.56.1/your_php_dir
      # 这里我新建了个用户来共享文件夹
      o: username=cifs,password=cifs,file_mode=0777,dir_mode=0777
```

```jsonc
// .devcontainer/devcontainer.json
// See https://aka.ms/vscode-remote/devcontainer.json for format details.
{
	"name": "PHP 7",
	"dockerComposeFile": [
    "../docker-compose.yml", // 根目录的
    "./docker-compose.yml" // .devcontainer 的
    // 这两个文件会合并后再运行
  ],
  // 要在其中打开 vscode 的容器服务
	"service": "php",
  // 要打开的文件夹
	"workspaceFolder": "/www/",
  // 要安装的扩展
	"extensions": [
		// "eamodio.gitlens"
	],
	"settings": {
    // 要在里面使用的命令行, 默认是 sh, 最好改下
		"terminal.integrated.shell.linux": "/bin/bash"
	},
}

```

感觉描述的又不顺, 总的来说就是可以在 vscode 使用 docker 搭建一个干净一致的开发环境了
