### ISSUE TITLE
fnproject 使用 dockerc-compose 部署

### ISSUE THREAD

**Issue by shynome** [shynome/shynome.github.io#27]
`docker-compose.yml` 文件内容
```yml
version: '3.6'

services: 

  postgres:
    image: postgres:11.4-alpine@sha256:0058d56b16eda79d34fb7b6987cee0b26df495cb39bbf9a1e2fdab411b08648c
    ports:  [ { mode: host, protocol: tcp, target: 5432, published: 5432 } ]
    volumes: [ 'pg_data:/var/lib/postgresql/data' ]
    environment: 
      POSTGRES_DB: 'funcs'
      POSTGRES_USER: 'funcs'
      POSTGRES_PASSWORD: 'postgrespass'
    logging: &logging
      options: { max-size: "200k", max-file: "10" }
    deploy: &deploy
      endpoint_mode: dnsrr
      resources: { limits: { memory: 1G } }
      restart_policy: { condition: on-failure, max_attempts: 3 }

  api:
    image: fnproject/fnserver:0.3.719@sha256:1d1624fc884f9d1a6c781458846da28a133b2ba7a2e995bed1b14d6d5dcf217e
    entrypoint: [ '/app/fnserver' ]
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock', '/tmp:/tmp' ]
    ports:  [ { mode: host, protocol: tcp, target: 8080, published: 8080 } ]
    environment: 
      FN_NODE_TYPE: api
      FN_PUBLIC_LB_URL: http://172.17.0.1:8181
      FN_DB_URL: postgres://funcs:postgrespass@postgres/funcs?sslmode=disable
    logging: { <<: *logging }
    deploy: { <<: *deploy }

  lb: 
    image: fnproject/fnserver:0.3.719@sha256:1d1624fc884f9d1a6c781458846da28a133b2ba7a2e995bed1b14d6d5dcf217e
    entrypoint: [ '/app/fnserver' ]
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock', '/tmp:/tmp' ]
    ports: [ { mode: host, protocol: tcp, target: 8080, published: 8181 } ]
    environment: 
      FN_NODE_TYPE: lb
      FN_RUNNER_API_URL: http://172.17.0.1:8080
      FN_RUNNER_ADDRESSES: 172.17.0.1:9190
    logging: { <<: *logging }
    deploy: { <<: *deploy }
  
  runners:
    image: fnproject/fnserver:0.3.719@sha256:1d1624fc884f9d1a6c781458846da28a133b2ba7a2e995bed1b14d6d5dcf217e
    entrypoint: [ '/app/fnserver' ]
    ports: [ { mode: host, protocol: tcp, target: 9190, published: 9190 } ]
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock', '/tmp:/tmp' ]
    environment: 
      FN_NODE_TYPE: pure-runner
    logging: { <<: *logging }
    deploy: 
      <<: *deploy
      mode: global
  
volumes: 
  pg_data: 
```

使用 `docker stack deploy -c docker-compose.yml fn` 部署
