### ISSUE TITLE
vscode 启用 GraphQL 代码提示指南

### ISSUE THREAD

**Issue by shynome** [shynome/shynome.github.io#31]
vscode 启用 GraphQL 代码提示指南

前段时间用了 `thrift` , 感觉很好用, 就是看`nodejs`的服务器代码写的感觉性能不行,
于是想优化下, 没想到越看越觉得`thrift`已经在迈入死亡了, 维护的人不多, issue 发出去收不到回应;
`npm` 发包没有预先的测试包直接发到正式包上, 现在直接安装 `thrift` 安装到的 `0.13.0` 版本会
无法创建 `web server`, 因为这个版本的包只包含了前端代码. 于是又捡起了之前因为没有代码提示而抛弃的
`GrpahQL`, 虽然性能可能不好, 但是有人在维护呀, 这篇文章教你如何使用 `Apollo GraphQL` 扩展在 `vscode` 开启 `GraphQl` 提示

### 第一步, 安装扩展

安装 `Apollo GraphQL`

### 第二步, 安装依赖包

新建一个文件夹进行测试

```sh
mkdir gql-tips-test && cd gql-tips-test && yarn init -y
```

安装依赖

```sh
yarn add -D graphql @graphql-codegen/cli @graphql-codegen/typescript
# 安装 ts 所需要的 graphql-codegen plugins
# resolvers 是给服务端用的, 不需要的话可以不要
# 具体的可使用 yarn graphql-codegen init 查看
yarn add -D @graphql-codegen/introspection @graphql-codegen/typescript-operations @graphql-codegen/typescript-resolvers
```

### 第三步, 设置测试文件

**注:** 以下目录的根路径都是上面创建的测试文件夹

复制以下内容到 `codegen.yml`

```yml
overwrite: true
schema: "graphql/*.graphql"
document: "graphql/*.graphql"
generates:
  graphql/codegen/index.d.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-resolvers"
  # 重要, apollo graphql 就是使用这个文件进行代码提示的
  graphql/codegen/index.schema.json:
    plugins:
      - "introspection"
```

复制以下内容到 `apollo.config.js`

配置文件详情: https://www.apollographql.com/docs/devtools/apollo-config/#option-3-link-a-schema-from-a-local-file

```js
module.exports = {
  client: {
    service: {
      name: "lcoal server",
      localSchemaFile: "graphql/codegen/index.schema.json"
    },
    // 默认是 `src/` 下的文件, 我用 `next.js` 客户端代码都在 `pages/` 下, 所以改成 `pages/`
    includes: ["./pages/**/*.{gql,ts,tsx,graphql}"]
  }
};
```

复制以下内容到 `graphql/schema.graphql` 后执行 `yarn graphql-codegen` 生成 `graphql/codegen/index.schema.json` 和 `graphql/codegen/index.d.ts` 文件

然后选择重新加载窗口 (按 `F1` 或 `Ctrl+Shift+P` 跳出命令输入框, 输入 `reload` 会有一个 `Reload Windows` 的选项出来, 选中回车即可)

```graphql
type User {
  # 用户昵称
  name: String
  # 用户邮箱
  email: String!
}

type Query {
  # 随机获得一个用户的信息
  user: User
}
```

### 第四步, 使用代码提示

复制以下内容到 `pages/a.ts`, 然后鼠标移到 `email` 上会有注释提示, 点击使输入光标在 `user` 块内, 按 `Ctrl+Space` 会有类似函数一样的可选项提示

**提示:**

- 修改了 `graphql/schema.graphql` 需要重新生成了 `index.schema.json` 并 `reload schema` 才会有修改后的提示.  
  `reload shema` 操作是按 `F1` 输入 `reload shema` 选中对应选项回车即可
- 右下角有个 `Apollo` 的按钮, 点击可以查看日志

```ts
declare var gql;

gql`
  query user {
    user {
      email
    }
  }
`;
```
