### ISSUE TITLE
Docker swarm 模式下获取访问客户端的 ip 地址

### ISSUE THREAD

**Issue by shynome** [shynome/shynome.github.io#8]
最近尝试根据访问 ip 地址来做灰度发布, 但发现 docker swarm 模式访问 nginx 的 ip 地址都是 10.0.0.x 这样的 dcoker 内部网络地址, 后面在 issue 上找到解决方案, 把 ports 的发布模式改为 host
```
services:
  proxy:
    image: nginx
    ports:
    - { target: 80, published: 80, protocol: tcp, mode: host }
```
